### ISSUE TITLE
Is there a way to set a next version variable when the "dry run" option is set?

### ISSUE THREAD

**Issue by hapablap21** [lluchmk/semantic-release-ado#15]
It appears that semantic-release doesn't run prepare, publish, success and fail when the dry-run option is set.

**Comment by lluchmk** [comment]
Let me take a look at it this week, I think we could move the version assignation to verifyRelease, which will run even with dry-run set.

**Comment by lluchmk** [comment]
Sorry for the super late reply, I've moved the version variable assignment to the verifyRelease step on version 1.3.0. so now it will set it event when running with dry-run.

Closing the issue now, thanks!
