### ISSUE TITLE
Allow configuring behavior on nextRelease when there's no relevant changes.

### ISSUE THREAD

**Issue by lluchmk** [lluchmk/semantic-release-ado#3]
Versions 1.0.x didn't set the `nextRelease` variable when there's no relevant changes. 1.1.0 changed this behavior, setting the value to the previous versions.
A configuration option should be added to allow configuring this behavior.

Original comment:
I understand this feature but I was using the empty state of the ``nextRelease`` variable if there is no relevant change. Do you think it is possible to add an option to enable/disable this new feature. It would be great! Thank you all!

_Originally posted by @panquez in https://github.com/lluchmk/semantic-release-ado/pull/2#issuecomment-527066715_

**Comment by lluchmk** [comment]
Proposing the name of the config variable as `setWhenNoRelease`. I'm not really convinced with this name, but cant't come up with a better one.
Any thoughts on this @panquez?

**Comment by panquez** [comment]
It’s ok. Could also be something like setOnlyOnRelease ?

**Comment by lluchmk** [comment]
Version [1.2.0](https://github.com/lluchmk/semantic-release-ado/releases/tag/v1.2.0) adds the variable setOnlyOnRelease to define this behavior.

Thanks!

**Comment by panquez** [comment]
Thanks a lot for this change!
