### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by hmendezm** [lluchmk/semantic-release-ado#8]
Hi guys

Does sematic-release-ado generate CHANGELOG as well? if yes, is it using  conventional-changelog-config-spec ?

Best
Hmendezm

**Comment by lluchmk** [comment]
Hey there,

semantic-release-ado by itself won't generate the CHANGELOG, but take a look at the [release-notes-generator](https://github.com/semantic-release/release-notes-generator) and [changelog](https://github.com/semantic-release/changelog) plugins, which will do exactly that.

This project uses them both to generate and update the CHANGELOG , together with the github and git plugins to commit the changes automatically. You can see it in the [semantic-release config file](https://github.com/lluchmk/semantic-release-ado/blob/master/.releaserc).

Hope it helps!

**Comment by hmendezm** [comment]
Thanks IIuckmk for the info.
